# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
       php: 8.0
    tests:
            override:
                -
                    command: './vendor/bin/phpunit --coverage-clover=clover.xml'
                    coverage:
                        file: 'clover.xml'
                        format: 'clover'

